# Generated by Django 4.2.6 on 2023-10-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_alter_student_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='id',
            new_name='rollno',
        ),
    ]
