# Generated by Django 4.2.6 on 2023-10-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_rename_id_student_rollno'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('couse_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
    ]
