# Generated by Django 4.2.6 on 2023-10-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_course_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='fees',
        ),
        migrations.AddField(
            model_name='enroll',
            name='fees',
            field=models.IntegerField(default=0),
        ),
    ]
