# Generated by Django 4.2.6 on 2023-10-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0007_remove_course_fees_enroll_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='status',
            field=models.CharField(default='paid', max_length=100),
        ),
    ]
