# Generated by Django 4.2.6 on 2023-11-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0008_enroll_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='status',
            field=models.CharField(default='Not paid', max_length=100),
        ),
    ]
