# Generated by Django 5.0.2 on 2024-02-29 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0010_remove_enroll_couse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='couse_id',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='studentapp.course'),
        ),
    ]
